server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

  # 数据库连接配置
database:
  logger:
    path: "temp/logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default:
    link: "mysql:root:root@tcp(127.0.0.1:3306)/shop?parseTime=true&loc=Local"
    # link: "sqlite::@file(manifest/document/sqlite/focus.db)"
    debug: true


# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db: 1
    pass: 123456
    idleTimeout: 600

upload:
  path: "upload"