// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "myGoFrame/internal/logic/address"
	_ "myGoFrame/internal/logic/admin"
	_ "myGoFrame/internal/logic/article"
	_ "myGoFrame/internal/logic/bizctx"
	_ "myGoFrame/internal/logic/cart"
	_ "myGoFrame/internal/logic/category"
	_ "myGoFrame/internal/logic/collection"
	_ "myGoFrame/internal/logic/comment"
	_ "myGoFrame/internal/logic/coupon"
	_ "myGoFrame/internal/logic/data"
	_ "myGoFrame/internal/logic/file"
	_ "myGoFrame/internal/logic/goods"
	_ "myGoFrame/internal/logic/goods_options"
	_ "myGoFrame/internal/logic/login"
	_ "myGoFrame/internal/logic/middleware"
	_ "myGoFrame/internal/logic/order"
	_ "myGoFrame/internal/logic/order_goods_comments"
	_ "myGoFrame/internal/logic/permission"
	_ "myGoFrame/internal/logic/position"
	_ "myGoFrame/internal/logic/praise"
	_ "myGoFrame/internal/logic/refund"
	_ "myGoFrame/internal/logic/role"
	_ "myGoFrame/internal/logic/rotation"
	_ "myGoFrame/internal/logic/session"
	_ "myGoFrame/internal/logic/user"
	_ "myGoFrame/internal/logic/user_coupon"
)
